version: 0.1.4

case_name: "add_green"  # which is also the folder name
data_path_template: "data/{case_name}/point_cloud.npz"
temp_file_path_template: "temp_files/{case_name}/"

# working space settings
default_x_length: 296  # mm, from back to front
default_y_length: 523.3  # mm, from left to right
origin_label: "0"
x_axis_label: ["9", "8"]  # the last one can be used to define the axis length
y_axis_label: ["1", "2", "3"]  # the last one can be used to define the axis length

# trajecoty settings
smooth_size: 0
action_supported: ["contour", "behaviour"]
device_precision: 1  # mm
bulk_cutting_style: "cut_inward"  # "row_by_row" or "cut_inward"
surface_upscale: 10
spindle_radius: 5
