version: 0.1.1

case_name: "realsense_data_dark"  # which is also the folder name
data_path_template: "data/{case_name}/*.npz"
temp_file_path_template: "temp_files/{case_name}/"

# settings
action_supported: ["contour", "behaviour"]
device_precision: 1  # mm
surface_upscale: 10
trajectory_row_interval: 5
