version: 0.2.0

case_name: "zen_test"  # which is also the folder name
data_path_template: "data/{case_name}/point_cloud.npz"
temp_file_path_template: "temp_files/{case_name}/"

# working space settings
default_x_length: 296  # mm, from back to front
default_y_length: 523.3  # mm, from left to right
origin_label: "0"
x_axis_label: ["9", "8"]  # the last one can be used to define the axis length
y_axis_label: ["1", "2", "3"]  # the last one can be used to define the axis length

# mask extraction settings
smooth_size: 0
surface_upscale: 10
contour_mark: ["contour"]
behavior_mark: ["behavior_plane", "behavior_relief"]  # when detected as first, other will be ignored
device_precision: 1  # mm

# planning settings
bulk_cutting_style: "cut_inward"  # "cut_inward"
spindle_radius: 10
step_size: 
  plane: 10  # mm
  relief: 10  # mm
relief_slop:
  caving: 0.5  # z / x or y
  mount: 0.2  # z / x or y

# cutting settings
offset_z_level: 0  # mm (when cutting, it needs to be 0)
line_cutting_depth: 2.5  # mm (minus means nothing will happen)
bulk_carving_depth: 2.5  # mm (minus means nothing will happen)
depth_forward: 0.3  # mm (cut every this depth layer)
feed_rate: 15  # mm/min

# visualization settings
z_expension: 2  # ratio
