version: 0.1.5

case_name: "addTest02"  # which is also the folder name
data_path_template: "data/{case_name}/point_cloud.npz"
temp_file_path_template: "temp_files/{case_name}/"

# working space settings
default_x_length: 296  # mm, from back to front
default_y_length: 523.3  # mm, from left to right
origin_label: "0"
x_axis_label: ["9", "8"]  # the last one can be used to define the axis length
y_axis_label: ["1", "2", "3"]  # the last one can be used to define the axis length

# trajecoty settings
smooth_size: 0
contour_mark: ["contour"]
behavior_mark: ["behavior_plane", "behavior_relief"]
device_precision: 1  # mm
bulk_cutting_style: "cut_inward"  # "row_by_row" or "cut_inward"
surface_upscale: 10
spindle_radius: 5

# cutting settings
carving_depth: 2.5  # mm (minus means nothing will happen)
feed_rate: 15  # mm/min
