version: 0.4.1

case_name: "temp_case"  # which is also the folder name
data_path_template: "data/{case_name}/point_cloud.npz"
temp_file_path_template: "temp_files/{case_name}/"
case_folder_template: "data/{case_name}/"

# capture settings
exposure_level: 100
image_sampling_size: 20
depth_queue_size: 50

# working space settings
default_x_length: 296  # mm, from back to front
default_y_length: 523.3  # mm, from left to right
origin_label: "10"  # later needs to be "10"
x_axis_label: ["9", "8"]  # the last one can be used to define the axis length
y_axis_label: ["1", "2", "3"]  # the last one can be used to define the axis length

# mask extraction settings
smooth_size: 0
surface_upscale: 10
contour_mark: ["contour"]
behavior_mark: ["behavior_plane", "behavior_relief"]  # when detected as first, other will be ignored
device_precision: 1  # mm

# planning settings
bulk_cutting_style: "cut_inward"  # "cut_inward"
distance_metric: "euclidean" # "euclidean" or "chessboard"
spindle_radius: 5
step_size: 
  coarse: 10  # mm, all cutting steps, except the last one
  fine: 7  # mm, the last cutting step
relief_slop:
  caving: 0.19  # z / x or y
  mount: 0.3  # z / x or y
min_points_per_traj: 3

# cutting settings
offset_z_level: 0  # mm (decide this by comparing machine measured z level and the actual z level)
line_cutting_depth: 2  # mm (minus means nothing will happen)
bulk_carving_depth: 
  behavior_relief: 10.5  # mm (minus means nothing will happen)
  behavior_plane: 2  # mm (minus means nothing will happen)
depth_forward_steps: [3, 2, 1, 0.6, 0.4, 0.3, 0.2]  # mm
start_cutting_step: 0  # 0, 1, 2, 3, 4
feed_rate: 
  coarse: 20  # mm/min, all cutting rate, except the last one
  fine: 20  # mm/min, the last cutting rate

# visualization settings
z_expension: 3  # ratio
