version: 1.0.0

# Case settings
case_name: "default_case"  # which is also the folder name
data_path_template: "data/{case_name}/point_cloud.npz"
temp_file_path_template: "temp_files/{case_name}/"
case_folder_template: "data/{case_name}/"

# Uiversal settings
depth_map_height: 800  # pixel
depth_map_width: 1280  # pixel

# page 1: capture settings
exposure_level: 100
image_sampling_size: 20
depth_queue_size: 50

# page 2: working space settings
# In panel
origin_label: "10"  # later needs to be "11"
x_axis_label: ["9", "8"]  # the last one can be used to define the axis length
y_axis_label: ["1", "2", "3"]  # the last one can be used to define the axis length
z_min_level: 10  # mm
z_max_level: 60  # mm
dilation_size: 5
# Not in panel
default_x_length: 296  # mm, from back to front
default_y_length: 523.3  # mm, from left to right
surface_upscale: 10  # times

# Page3: color mask extraction & Centerline extraction
# In panel
smooth_size: 0
# Not in panel
color_value_setting_file: "src/mask/color_type_values.json"
contour_mark: ["contour"]
behavior_mark: ["behavior_plane", "behavior_relief"]  # when detected as first, other will be ignored

# Step4: Trajectory & Visualization & Gcode Generation
# In panel
spindle_radius: 5
line_cutting_depth: 2  # mm (minus means nothing will happen)
offset_z_level: 0  # mm (decide this by comparing machine measured z level and the actual z level)
bulk_carving_depth: 
  behavior_relief: 10.5  # mm (minus means nothing will happen)
  behavior_plane: 3  # mm (minus means nothing will happen)
relief_slop:
  carving: 0.19  # z / x or y
  mount: 0.3  # z / x or y
# Not in panel
bulk_cutting_style: "cut_inward"  # "cut_inward"
depth_forward_steps: [2, 1, 0.6, 0.4, 0.3, 0.2]  # mm
distance_metric: "euclidean" # "euclidean" or "chessboard"
start_cutting_step: 0  # 0, 1, 2, 3, 4
min_points_per_traj: 3
step_size: 
  coarse: 10  # mm, all cutting steps, except the last one
  fine: 7  # mm, the last cutting step
feed_rate: 
  coarse: 15  # mm/min, all cutting rate, except the last one
  fine: 15  # mm/min, the last cutting rate
device_precision: 1  # mm
z_expension: 2  # ratio for visualizing the z level






